# centroid_tracker.py
"""
Simple centroid‑based multi‑object tracker.

The tracker reads bounding‑box detections from a CSV (generated by the detection
script) and assigns stable IDs to each object across frames. It writes a new CSV
with the same columns plus an `object_id` column.

Usage:
    python centroid_tracker.py --input detections.csv --output tracked.csv

The algorithm is a classic Euclidean‑distance based tracker:
1. For each new frame, compute centroids of the incoming boxes.
2. Compute pairwise distances to existing object centroids.
3. Match the closest pairs under a distance threshold.
4. Unmatched detections are registered as new objects.
5. Objects not matched for `max_disappeared` consecutive frames are
   deregistered (removed from tracking).
"""

import argparse
import csv
from pathlib import Path
import math
from collections import OrderedDict

class CentroidTracker:
    def __init__(self, max_distance=75, max_disappeared=10):
        # Next available unique object ID
        self.next_object_id = 0
        # Mapping object_id -> (centroid_x, centroid_y)
        self.objects = OrderedDict()
        # How many consecutive frames an object has been missing
        self.disappeared = {}
        self.max_distance = max_distance
        self.max_disappeared = max_disappeared

    def register(self, centroid):
        self.objects[self.next_object_id] = centroid
        self.disappeared[self.next_object_id] = 0
        self.next_object_id += 1

    def deregister(self, object_id):
        # Record deregistration before removal for debug logging
        self.deregistered_this_frame.append(object_id)
        del self.objects[object_id]
        del self.disappeared[object_id]

    def update(self, detections):
        """Update tracker with a list of detections for the current frame.

        `detections` is a list of (x, y, w, h) tuples.
        Returns a dict mapping object_id -> (x, y, w, h).
        """
        # Reset per‑frame logs
        self.registered_this_frame = []
        self.deregistered_this_frame = []

        # No detections: increment disappeared counters and possibly deregister
        if len(detections) == 0:
            for object_id in list(self.disappeared.keys()):
                self.disappeared[object_id] += 1
                if self.disappeared[object_id] > self.max_disappeared:
                    self.deregister(object_id)
            return {}

        # Compute centroids for incoming detections
        input_centroids = []
        for (x, y, w, h) in detections:
            cx = x + w / 2.0
            cy = y + h / 2.0
            input_centroids.append((cx, cy))

        if len(self.objects) == 0:
            # No existing objects – register all detections
            for centroid in input_centroids:
                self.register(centroid)
            # Return mapping of newly created IDs to boxes
            return {obj_id: detections[i] for i, obj_id in enumerate(range(self.next_object_id - len(detections), self.next_object_id))}

        # Prepare lists of current object IDs and centroids
        object_ids = list(self.objects.keys())
        object_centroids = list(self.objects.values())

        # Compute distance matrix between each pair of object centroid and input centroid
        distance_matrix = []
        for oc in object_centroids:
            row = []
            for ic in input_centroids:
                d = math.hypot(oc[0] - ic[0], oc[1] - ic[1])
                row.append(d)
            distance_matrix.append(row)

        # Greedy matching: find smallest distances first
        used_rows = set()
        used_cols = set()
        assignments = {}

        while True:
            min_val = None
            min_pos = None
            for r in range(len(distance_matrix)):
                if r in used_rows:
                    continue
                for c in range(len(distance_matrix[0])):
                    if c in used_cols:
                        continue
                    val = distance_matrix[r][c]
                    if min_val is None or val < min_val:
                        min_val = val
                        min_pos = (r, c)
            if min_pos is None or min_val > self.max_distance:
                break
            r, c = min_pos
            used_rows.add(r)
            used_cols.add(c)
            object_id = object_ids[r]
            self.objects[object_id] = input_centroids[c]
            self.disappeared[object_id] = 0
            assignments[object_id] = detections[c]
            # Existing track matched – not a new registration

        # Process unmatched existing objects (increase disappeared count)
        for r in set(range(len(object_ids))) - used_rows:
            object_id = object_ids[r]
            self.disappeared[object_id] += 1
            if self.disappeared[object_id] > self.max_disappeared:
                self.deregister(object_id)

        # Register unmatched input detections as new objects
        for c in set(range(len(detections))) - used_cols:
            self.register(input_centroids[c])
            new_id = self.next_object_id - 1
            assignments[new_id] = detections[c]
            self.registered_this_frame.append(new_id)

        return assignments

def parse_csv(input_path: Path):
    """Parse detection CSV generated by `detect_skeletons.py`.

    The CSV includes a header and the columns:
        video_id,frame_number,skeleton_id,bbox_x,bbox_y,bbox_width,bbox_height,bbox_area,centroid_x,centroid_y
    For tracking we only need `frame_number`, `skeleton_id` and the bounding‑box values.
    Returns a dict mapping each frame (int) to a list of (skeleton_id, (x, y, w, h)) tuples.
    """
    frame_dict = {}
    with open(input_path, newline="") as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            try:
                frame = int(row["frame_number"])
                skeleton_id = row["skeleton_id"]
                x = int(float(row["bbox_x"]))
                y = int(float(row["bbox_y"]))
                w = int(float(row["bbox_width"]))
                h = int(float(row["bbox_height"]))
                frame_dict.setdefault(frame, []).append((skeleton_id, (x, y, w, h)))
            except (KeyError, ValueError):
                continue
    return frame_dict

def write_tracked_csv(output_path: Path, tracked_data):
    """Write tracked results.

    Columns: `frame, object_id, x, y, w, h`
    """
    with open(output_path, "w", newline="") as csvfile:
        writer = csv.writer(csvfile)
        for frame, objs in sorted(tracked_data.items()):
            for object_id, bbox in objs.items():
                x, y, w, h = bbox
                writer.writerow([frame, object_id, x, y, w, h])

def main():
    parser = argparse.ArgumentParser(description="Centroid based multi‑object tracker")
    parser.add_argument("--input", required=True, help="Path to detection CSV (frame,x,y,w,h)")
    parser.add_argument("--output", required=True, help="Path to write tracked CSV (frame,object_id,x,y,w,h)")
    parser.add_argument("--debug", help="Path to optional debug CSV (writes frame,track_id,centroid_x,centroid_y,new_id flag)")
    parser.add_argument("--max-distance", type=int, default=75, help="Maximum centroid distance for matching (pixels)")
    parser.add_argument("--max-disappeared", type=int, default=5, help="Frames to wait before deregistering a lost object")
    args = parser.parse_args()

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    debug_path = args.debug
    debug_file = None
    debug_writer = None
    if debug_path:
        Path(debug_path).parent.mkdir(parents=True, exist_ok=True)
        debug_file = open(debug_path, "w", newline="")
        debug_writer = csv.writer(debug_file)
        debug_writer.writerow(["frame", "detected_ids", "matched_track_ids", "new_ids", "deregistered_ids"])
    input_path = Path(args.input)
    if not input_path.is_file():
        raise FileNotFoundError(
            f"Detection CSV not found: {input_path.resolve()}\n"
            "Run detect_skeletons.py first, e.g.:\n"
            '  python scripts/detect_skeletons.py --input "path/to/video.mp4" '
            '--csv "Subj_2_part_75_detections.csv"'
        )

    # Load detections from CSV
    detections_by_frame = parse_csv(input_path)

    tracker = CentroidTracker(max_distance=args.max_distance, max_disappeared=args.max_disappeared)
    tracked_by_frame = {}
    previous_ids = set()
    for frame in sorted(detections_by_frame.keys()):
        raw = detections_by_frame[frame]
        # Extract skeleton IDs for reporting and bounding‑box tuples for tracking
        detected_ids = [int(skel) for skel, _ in raw]
        detections = [bbox for _, bbox in raw]
        assignments = tracker.update(detections)
        # Determine new IDs (those not present before this frame)
        current_ids = set(tracker.objects.keys())
        new_ids = current_ids - previous_ids
        # Write debug rows for each active track
        # Write detailed debug information
        if debug_writer:
            debug_writer.writerow([
                frame,
                "|".join(map(str, detected_ids)),                # detected skeleton IDs
                "|".join(map(str, sorted(assignments.keys()))),   # matched track IDs
                "|".join(map(str, tracker.registered_this_frame)),
                "|".join(map(str, tracker.deregistered_this_frame))
            ])
        tracked_by_frame[frame] = assignments
        # Update previous_ids for next iteration
        previous_ids = current_ids

    if debug_file:
        debug_file.close()
    # Write tracked results to CSV
    write_tracked_csv(output_path, tracked_by_frame)
    print(f"Tracked results written to {args.output}")

if __name__ == "__main__":
    main()
