# filter_child_sequences.py
"""filter_child_sequences.py

Iterates over all ``*_child_sequence.csv`` files in the project and validates each
according to the following criteria:

1️⃣ The file exists (obviously, we only iterate over existing files).
2️⃣ Contains at least 30 data rows (frames).
3️⃣ All centroid columns ``centroid_x`` and ``centroid_y`` contain finite numeric
   values.
4️⃣ All bounding‑box columns ``bbox_width``, ``bbox_height``, ``bbox_area`` are
   finite numeric and greater than zero.
5️⃣ The file is not empty (covered by the row‑count check).

If a file passes all checks its corresponding video identifier (the stem of the
CSV name, e.g. ``Subj_2_part_62``) is written to ``accepted_videos.txt``.  If it
fails, a line is appended to ``rejected_videos.csv`` with columns
``video_id,rejection_reason``.

The script is deliberately lightweight – it uses only the Python standard
library and works on Windows (the repository’s default environment).
"""

import csv
import sys
import math
from pathlib import Path
from collections import defaultdict

# ---------------------------------------------------------------------------
# Configuration – can be tweaked if needed
# ---------------------------------------------------------------------------
MIN_FRAMES = 30
# Column names expected in the child sequence CSV (generated by
# ``extract_child_sequence.py``)
COLUMNS = [
    "frame_number",
    "centroid_x",
    "centroid_y",
    "bbox_width",
    "bbox_height",
    "bbox_area",
]

def is_finite_number(value: str) -> bool:
    """Return True if *value* can be parsed as a finite float.
    Empty strings, ``nan`` or ``inf`` are considered invalid.
    """
    try:
        f = float(value)
        return math.isfinite(f)
    except ValueError:
        return False

def validate_child_sequence(csv_path: Path) -> (bool, str):
    """Validate a single ``*_child_sequence.csv`` file.
    Returns ``(True, "")`` if the file passes all checks, otherwise ``(False,
    reason)`` where *reason* is a short machine‑readable tag.
    """
    if not csv_path.is_file():
        return False, "missing_file"

    with open(csv_path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        # Ensure the required columns are present
        if not all(col in reader.fieldnames for col in COLUMNS):
            return False, "invalid_header"

        rows = list(reader)
        if len(rows) < MIN_FRAMES:
            return False, "too_few_frames"

        for i, row in enumerate(rows, start=1):
            # Centroid checks
            if not (is_finite_number(row["centroid_x"]) and is_finite_number(row["centroid_y"])):
                return False, f"invalid_centroid_row_{i}"
            # BBox checks – width, height, area must be > 0 and finite
            try:
                w = float(row["bbox_width"])
                h = float(row["bbox_height"])
                a = float(row["bbox_area"])
                if not (w > 0 and h > 0 and a > 0 and math.isfinite(w) and math.isfinite(h) and math.isfinite(a)):
                    return False, f"invalid_bbox_row_{i}"
            except ValueError:
                return False, f"invalid_bbox_row_{i}"

    # Passed all checks
    return True, ""

def main():
    from path_config import CHILD_SEQUENCES_DIR, FILTERING_DIR, REPORTS_ROOT
    import csv
    import os

    # Load selected videos mapping
    selected_path = REPORTS_ROOT / "selected_videos.csv"
    selected_map = {}
    if selected_path.is_file():
        with open(selected_path, newline="", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                uid = row["unique_video_id"].strip()
                selected_map[uid] = {
                    "unique_video_id": uid,
                    "video_id": row.get("video_id", "").strip(),
                    "split": row.get("split", ""),
                    "label": row.get("label", ""),
                }
    else:
        print(f"Warning: selected videos file not found at {selected_path}")

    # Child sequence CSVs are written by extract_child_sequence.py
    sequence_files = sorted(CHILD_SEQUENCES_DIR.glob("*_child_sequence.csv"))

    rejected_path = FILTERING_DIR / "rejected_videos.csv"
    accepted_path = FILTERING_DIR / "accepted_videos.txt"
    audit_path = FILTERING_DIR / "filter_audit.csv"

    # Open output files (overwrite any previous run)
    rej_file = open(rejected_path, "w", newline="", encoding="utf-8")
    rej_writer = csv.writer(rej_file)
    rej_writer.writerow(["video_id", "rejection_reason"])

    acc_file = open(accepted_path, "w", encoding="utf-8")
    audit_file = open(audit_path, "w", newline="", encoding="utf-8")
    audit_writer = csv.writer(audit_file)
    audit_writer.writerow(["unique_video_id", "video_id", "split", "label", "accepted", "rejection_reason"])

    accepted_count = 0
    rejected_count = 0

    for seq_file in sequence_files:
        unique_video_id = seq_file.stem.replace("_child_sequence", "")
        ok, reason = validate_child_sequence(seq_file)
        meta = selected_map.get(unique_video_id, {"unique_video_id": unique_video_id, "video_id": "", "split": "", "label": ""})
        if ok:
            acc_file.write(unique_video_id + "\n")
            accepted_count += 1
            audit_writer.writerow([unique_video_id, meta["video_id"], meta["split"], meta["label"], "True", ""])
        else:
            rej_writer.writerow([unique_video_id, reason])
            rejected_count += 1
            audit_writer.writerow([unique_video_id, meta["video_id"], meta["split"], meta["label"], "False", reason])

    rej_file.close()
    acc_file.close()
    audit_file.close()

    print(f"Filter audit generated: {audit_path}")
    print(f"Processed {len(sequence_files)} child sequence files.")
    print(f"Accepted: {accepted_count}, Rejected: {rejected_count}")

if __name__ == "__main__":
    main()
