import csv
import logging
import sys
from pathlib import Path

from path_config import PROJECT_ROOT


def count_videos(data_root: Path) -> dict[str, int]:
    """Return a dict with video counts for each of the four groups."""
    counts = {
        "training_asd": 0,
        "training_td": 0,
        "testing_asd": 0,
        "testing_td": 0,
    }
    for split in ("training_set", "testing_set"):
        for label in ("asd", "td"):
            folder = data_root / split / label
            if not folder.is_dir():
                continue
            n = len(list(folder.rglob("*.mp4")))
            key = f"{'training' if split.startswith('training') else 'testing'}_{label}"
            counts[key] = n
    return counts


def read_selected(csv_path: Path) -> dict[str, int]:
    """Read the selected_videos.csv generated by run_pipeline and count per group."""
    counts = {
        "training_asd": 0,
        "training_td": 0,
        "testing_asd": 0,
        "testing_td": 0,
    }
    if not csv_path.is_file():
        logging.error("Selected videos file not found: %s", csv_path)
        return counts
    with open(csv_path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            split = row["split"].strip().lower()
            label = row["label"].strip().lower()
            key = f"{split}_{label}"
            if key in counts:
                counts[key] += 1
    return counts


def main():
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    data_root = PROJECT_ROOT / "autism_data_anonymized" / "autism_data_anonymized"
    discovery = count_videos(data_root)
    logging.info("Video discovery counts:")
    for k, v in discovery.items():
        logging.info("  %s: %d", k, v)

    selected_path = PROJECT_ROOT / "logs" / "selected_videos.csv"
    selected = read_selected(selected_path)
    logging.info("Selected video counts (from %s):", selected_path)
    for k, v in selected.items():
        logging.info("  %s: %d", k, v)

    # Simple sanity check
    for k in discovery:
        if selected.get(k, 0) > discovery[k]:
            logging.warning("Selected %s videos (%d) exceeds discovered %d", k, selected[k], discovery[k])

if __name__ == "__main__":
    main()
